---
- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080 

  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      tags:
        - update-apt

    - name: NGINX | Install NGINX
      ansible.builtin.apt:
         name: nginx
         state: latest
      notify:
        - restart nginx
      tags:
        - install-nginx

    # - name: Remove default cofig
    #   ansible.builtin.file:
    #     path: /etc/nginx/conf.d/default.conf
    #     state: absent

    - name: NGINX | Create NGINX config file from template
      ansible.builtin.template:
         src: templates/nginx.conf.j2
         #dest: /etc/nginx/conf.d/{{ inventory_name }}.conf
         dest: /etc/nginx/sites-available/default
         backup: true
      
      notify:
        - reload nginx         
      tags:
        - nginx-configuration


  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded


